# Generated by Django 3.2.23 on 2023-12-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20231229_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
