# Generated by Django 3.2.23 on 2024-01-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20240102_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_submitted',
        ),
    ]
