# Generated by Django 3.2.23 on 2024-01-05 23:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/duktk6qg0/image/upload/v1704495408/profile_b4aljb.jpg', max_length=255, verbose_name='image'),
        ),
    ]
